### ISSUE TITLE
Add linter

### ISSUE THREAD

**Issue by nitindermohan** [oakestra/oakestra#125]
# Proposal

We need to add a GitHub workflow with a linter for the code. The linter should take into consideration: 

- Root Orchestrator
   - System Manager (python)
   - Cloud scheduler (python)
- Cluster Orchestrator
   - Cluster scheduler (python)
   - cluster manager (python)
- NodeEngine (golang)

**Comment by Malyuk-A** [comment]
I will resolve this together with this ticket: https://github.com/oakestra/oakestra/issues/234

**Comment by nitindermohan** [comment]
This was addressed in #234. Closing!
