### ISSUE TITLE
Plugin manager for Oakestra

### ISSUE THREAD

**Issue by nitindermohan** [oakestra/oakestra#162]
A plugin manager for Oakestra that houses all additional features as composable code blocks. The plugins can be hosted in a marketplace where interested users can browse through and install features that might interest them on demand. Think of this as borrowing ideas from marketplace for VScode. 

The feature extension requires 
1. decoupling the basecode and plugin code, 
2. creating an install method for fetching and integrating the code from remote server.

**Comment by giobart** [comment]
Implemented in #169
