### ISSUE TITLE
unused node engine port should be removed 

### ISSUE THREAD

**Issue by giobart** [oakestra/oakestra#203]
## Short
Node engine is currently using a port parameter as part of the model that is not used anywhere. This should be removed. 

[https://github.com/oakestra/oakestra/blob/f54812f3444392584ae480ad508fcfc74f0e73ab/go_node_engine/model/Node.go#L206](https://github.com/oakestra/oakestra/blob/f54812f3444392584ae480ad508fcfc74f0e73ab/go_node_engine/model/Node.go#L206)

## Proposal 
This method can be removed because this port field is not used on the NodeEngine. Also, the "port" field [here](https://github.com/oakestra/oakestra/blob/f54812f3444392584ae480ad508fcfc74f0e73ab/go_node_engine/model/Node.go#L28) and [here](https://github.com/oakestra/oakestra/blob/f54812f3444392584ae480ad508fcfc74f0e73ab/cluster_orchestrator/cluster-manager/mongodb_client.py#L235C1-L238C45) can be removed as well. 

## Status
Discussed

## Checklist
- [x] Discussed
- [ ] Solved
- [ ] Tested

**Comment by TFphoenix** [comment]
Should these just be deleted, or do they have further dependency implications, that should be checked for?

**Comment by giobart** [comment]
They should not have any dependency left, as far as I see, but testing this afterward shouldn't hurt :D
