### ISSUE TITLE
Use transactions for mongodb

### ISSUE THREAD

**Issue by melkodary** [oakestra/oakestra#230]
## Short
Currently, several scenarios where values are inserted into mongodb then removed because of some invalidation. For example, when creating an application and its microservices with one request - first the appliation is added, next services are added, and at last the services are deployed to a machine. If deployment fails we remove manually the application from the database.

## Proposal
Proposed solution is to have a transaction and then commit when all parts of the process are complete, otherwise rollback. This way it's more efficient.

## Ratio
Transactions are fundamental need for databases. Also it provides atomicity & consistency - either changes are commited or rejected. It's also more effiecient.

## Impact
- application_blueprints::ApplicationController::post -> application_management::register_app
- services_blueprints::ServiceControllerPost::post -> service_management::create_services_of_app

While there are other parts of the system that communicates with the database, but creating transactions for those parts are not necessary. 

## Development time
< 1 week

## Status

After some scoping, I realized that the documents are distributed across several databases. In general, a session or transaction can span multiple databases, ensuring that all operations across those databases are treated as a single unit of work. This means that if any error occurs during the transaction, all changes made to all involved databases will be rolled back, preserving data integrity. 

- check how this is done with mongodb.

## Checklist
 
- [ ] Discussed
- [ ] Documented
- [ ] Implemented
- [ ] Tested

**Comment by giobart** [comment]
@melkodary thank you for the issue, very good point! Do you have the bandwidth to tackle this issue?

**Comment by melkodary** [comment]
@giobart Definitely! I just wanted to get your opinion on it first before proceeding. Also it needs better scoping, which I would revise first, and if a lot of parts of the code are impacted, then I'll break it down into several PR(s).
