### ISSUE TITLE
Add a (Python) code styling guideline, linter, & CI job for style checking

### ISSUE THREAD

**Issue by Malyuk-A** [oakestra/oakestra#234]
## Short
Add a (initially Python) code styling guideline, linter, & CI job for checking that style

## Proposal
Because this project is growing and new people will be joining it makes sense to find a common ground when it comes to code style. (Including naming conventions, linters, documentation, etc.)

I am aware that the dashboard already utilizes prettier & eslint.
The Python part of the codebase however seems to be lacking any kind of style enforcement.

I would recommend starting with tiny changes to get everyone on board and introduce more rules/tools as time goes on and ease the transition/adjustment time. Code style should support the developers and not punish them during their work.

Python Tools I am working with in my job that I can recommend are:
- formatter: https://github.com/psf/black
- linter https://flake8.pycqa.org/en/latest/
- import sorter: https://github.com/PyCQA/isort
- general style guide: https://peps.python.org/pep-0008/

The good part about these tools is that they can be easily included as VSCode extensions.

Further ideas:
- Settle on a naming convention (based on e.g. pep8)
- Add (more) helpful comments, especially for newcomers. (This can easily become a burden and lead to "overengineering", so we need to agree on when and how comments should be used -> Preferably with a "commenting style" such that readability is improved)
- Think about introducing Python's type hints <- Even further increases in readability & comprehension
-- https://docs.python.org/3/library/typing.html
-- https://docs.python.org/3.7/library/typing.html

E.g. the "How to" setup and or even naming conventions/style guides can/should be written down in a dedicated place.
We could place them into the oakestra.io/docs/contribute section, or even write them down in markdown files in the repo, so that they can easily be referenced during development.

A CI job would also be necessary so that every contribution is checked for style violations to stay consistent and not introduce any new irregularities.

## Ratio
Currently, there seem to be no code styling rules or listers used in this project. Sooner or later this will lead to unnecessary difficulties in the domains of readability, comprehension, refactorability, etc. Every large(r) project I have been working on utilized these standards to improve collaboration and code quality, thus Oakestra will benefit from this too.

## Impact
Depending on the strictness and amount of newly introduced rules and tools this could lead to adjusting almost every file in the oakestra repos.

## Development time
Ongoing process. The initial introduction of one or two "soft" linters and writing code-style documentation should not take more than a day. Adjusting the code base to these new rules can take up more time ~ a couple of days.

## Status
Looking for feedback. I am new to the project and I do not want to force anyone into adhering to new rules that a newcomer proposed. I want to make this a team effort where everyone is on board.

## Checklist
 
- [x] Discussed
- [x] Documented
- [x] Implemented
- [x] Tested

**Comment by giobart** [comment]
@Malyuk-A Can I assign this to you?

**Comment by Malyuk-A** [comment]
@giobart yes, go ahead 👍

**Comment by nitindermohan** [comment]
@Malyuk-A is this issue still being worked on? If yes, can you set its status appropriately in the roadmap?
