### ISSUE TITLE
New github-actions/workflows for checking Docker image builds during PR development

### ISSUE THREAD

**Issue by Malyuk-A** [oakestra/oakestra#260]
## Short
Add new workflows (github-actions) for checking if our Docker image builds still pass during PR development. Only trigger them for PRs that modify the Dockerfiles or their related directories (i.e. do not run them on every commit for every branch).

## Proposal
Same as *Short* + maybe unify & simplify the existing workflows for the images, they are pretty much the same, thus a lot of code-duplication is going on.

## Ratio
Recently we merged a PR that adjusted one Dockerfile very slightly. Local builds worked perfectly fine. There are currently also no PR related action-checks that showed any issues with the changes. So we merged the MR but only then actions were triggered to build and push the images to the registry and they suddenly showed issues and failed. (Github runner perspective). This would not have happened if we had actions in place to check image builds during PR development.
At the company I am working at we also run builds in the CI for testing on MRs/PRs without pushing them, for safety reasons.

## Impact
Github Actions

## Development time
Adding the checks clumsily can be done in one hour.
Doing this properly and maybe refactoring the existing image build/push workflows can take multiple hours - 1 day max.

## Status
Looking for feedback. (I already know that this is doable because I tried it out temporarily and I have a good idea of how to make this properly.)

## Checklist
 
- [ ] Discussed
- [ ] Documented
- [ ] Implemented
- [ ] Tested

**Comment by giobart** [comment]
Hey that's a very good idea!
