### ISSUE TITLE
Pre-Push hook for linting

### ISSUE THREAD

**Issue by melkodary** [oakestra/oakestra#278]
## Short
Git pipelines often fail because of linting issues, which then requires another commit to fix it, leaving the history of commits just filled with "liniting fix".

## Proposal
One solution is to just squash to correct the history but then you'll need to force push which is not really ideal. The proposed solution is to have a pre-push hook configured. This way locally one knows that they can't push unless the linting issues are fixed.

## Ratio
Not  a priority, but fairly easy to win and its a quick win.

## Impact
No impact

## Development time
<1 hr

## Checklist
 
- [x] Discussed
- [x] Documented
- [x] Implemented

**Comment by Malyuk-A** [comment]
Out of curiosity, why are git force pushes not ideal?  😅

> ... are but then you'll need to force push which is not really ideal.

E.g. this is the git workflow of the company I work for and we use force pushes.
[git-workflow.pdf](https://github.com/oakestra/oakestra/files/14358559/git-workflow.pdf)

**Comment by melkodary** [comment]
> Out of curiosity, why are git force pushes not ideal? 😅
> 
> > ... are but then you'll need to force push which is not really ideal.
> 
> E.g. this is the git workflow of the company I work for and we use force pushes. [git-workflow.pdf](https://github.com/oakestra/oakestra/files/14358559/git-workflow.pdf)

Well you need to be careful to not override remote commits and one might forget to use `with lease` option. Point is one has to be very careful about force pushing. Also the idea of rewriting history is something I try to avoid. I understand that people sometimes they have to force push anyways because of rebasing but that's another discussion I guess of `rebasing` vs `merging`.
