### ISSUE TITLE
Create pre-commit hooks for isort and black checks

### ISSUE THREAD

**Issue by smnzlnsk** [oakestra/oakestra#287]
## Short
On commit push isort is very sensitive towards incorrectly ordered imports and thus fails the check. To prevent a new commit with a run isort, create pre-commit hooks running black and isort in the desired order to prevent such small errors. 

## Proposal
Something along the lines of https://pre-commit.com/#usage

## Ratio
prevents any future 'satisfy-linter/isort and black' commits. Also makes the linter checks more accessible for newcomers.

## Impact
.git/hooks/pre-commit

## Development time
1 day

## Status
Looking for feedback

## Checklist
 
- [ ] Discussed
- [ ] Documented
- [ ] Implemented
- [ ] Tested

**Comment by melkodary** [comment]
I believe this is a duplicate. Correct me if I am wrong or missing something. https://github.com/oakestra/oakestra/pull/279

**Comment by smnzlnsk** [comment]
My bad. Closed, because duplicate with #279
