### ISSUE TITLE
Replace WebSocket Server with GRPC Server

### ISSUE THREAD

**Issue by JakobKe** [oakestra/oakestra#316]
## Short
Replace the WebSocket server in the root component with a gRPC server.
 
## Proposal
The Go programming language lacks robust library support for WebSockets. For this reason, I propose implementing a gRPC server as a replacement for the WebSocket server.

## Impact
Root System Manager, Cluster System Manager

## Development time
1 day

## Status
The gRPC server for the root component has been developed; find the relevant branch attached. The Cluster component is currently developed only in Go and not in Python; this needs to be addressed. 

## Attachements:
- [GRPC Server in Root Component](https://github.com/JakobKe/oakestra-master-thesis/blob/a3a806d66c4e68cf58138ff8b4c76fb8dd899f38/root_orchestrator/system-manager-python/system_manager.py#L142):
- [GRPC Server generated Files](https://github.com/JakobKe/oakestra-master-thesis/tree/develop/root_orchestrator/system-manager-python/proto) 

## Checklist
 
- [ ] Discussed
- [ ] Documented
- [ ] Implemented
- [ ] Tested

**Comment by nitindermohan** [comment]
I think @TheDarkPyotr is already working on this. Can you comment with the plan Luca?

**Comment by TheDarkPyotr** [comment]
> I think @TheDarkPyotr is already working on this. Can you comment with the plan Luca?
Exactly, I'm working on this: I have rewritten the cluster registration using gRPC and seems to work properly, I'm fixing minor bugs as it seems to affects the background job execution after clusterID assignation. 👍🏼
