### ISSUE TITLE
Proper transparent Versioning for NodeEngine & NetManager

### ISSUE THREAD

**Issue by Malyuk-A** [oakestra/oakestra#341]
## Short
Add a flag or output to the NodeEngine and NetManager (binaries) to easily figure out what version they are (i.e. what tag or commit they where build on)

## Proposal
This versioning can be done via custom hacks or by using sophisticated frameworks like [cobra](https://github.com/spf13/cobra) (The latter should be preferred)

## Ratio
Currently there is no trivial way to figure out or compare what version someone is using for the NodeEngine or NetManager - which can lead to compatibility, migration, etc issues e.g. when debugging.

## Impact
- NetManager & NodeEngine

## Development time
Depends on your know-how: A few hours to 1 day.

## Status
Discussed

## Checklist
 
- [x] Discussed
- [ ] Documented
- [ ] Implemented
- [ ] Tested

**Comment by giobart** [comment]
My suggestion here is to change the entire parameter and flag parsing using Cobra https://github.com/spf13/cobra
This supports a default flag --version that we can customize. 

I'll take care of that ;)
