### ISSUE TITLE
Integrate more advanced configuration options

### ISSUE THREAD

**Issue by sbaeurle** [oakestra/oakestra#71]
@giobart for the go based implementation please take a look at https://github.com/spf13/cobra as well as https://github.com/spf13/viper for both command generation as well as configuration management.

Creating this issue, as discussed today.

**Comment by nitindermohan** [comment]
Did we manage to solve these configuration problems?

**Comment by sbaeurle** [comment]
im not sure, maybe @giobart can give more input on this

**Comment by giobart** [comment]
We don't have any problem per se, but cobra would definitely be nice to have for the configurations both on our NodeEngine and the NetManager

**Comment by sbaeurle** [comment]
@giobart if for some mysterious reason I do find some time apart from working, I will evaluate cobra and push a PR for it :)

**Comment by giobart** [comment]
fixed in #341
