### ISSUE TITLE
Special characters filter

### ISSUE THREAD

**Issue by giobart** [oakestra/oakestra#85]
## Short
We must reject all service/app/namespace names including special characters.

## Proposal
Our service and app registration API must reject all names, including any sort of special chars. Using a regex should be enough to filter out these odd symbols in service/app names and service/app namespaces. The fully qualified service name must contain only standard latin characters. 

## Ratio
Fully qualified service names can be used on DNS and to address services internally. It is a very bad habit to have special characters in them.

## Impact
Potential impact system manager API, but I'd add the same check on the cluster manager component, as well as the networking components. Finally, the front-end must integrate the regex in the textbook. 

## Development time
A week at most

## Status
Looking for help

## Checklist
 
- [ ] Discussed
- [ ] Documented
- [ ] Implemented
- [ ] Tested

**Comment by nitindermohan** [comment]
What odd special characters should we exclude. Can you propose a list?
