### ISSUE TITLE
Adding Unikernels as an alternative deployment target.

### ISSUE THREAD

**Issue by Sabanic-P** [oakestra/oakestra#89]
## Short
Adding Unikernels as a deployment target for Oakestra. 

## Proposal
Adding another supported technology to Oakestra. 
This enables the deployment of unikernels as a alternative to Containers.
The change include the extension of runtimes available in Oakestra as well as adding the ability for the Root and Cluster to properly schedule for the new runtime. This new runtime can be used to execute unikernel with 
Oakestra and is based on QEMU.

## Ratio
Unikernels offer an alternative to containers and can offer a lower resource consumption and memory footprint.

## Impact
The changes impact all components of Oakestra from node to root. The changes do not affect the execution of
containers.

## Status
Currently under development. 

## Checklist
 
- [x] Discussed
- [ ] Documented
- [x] Implemented
- [ ] Tested

**Comment by giobart** [comment]
<img width="1214" alt="image" src="https://github.com/oakestra/oakestra/assets/25887329/9c09265f-f38a-4652-b0a8-564574de7608">

## What Changed? 
- NodeEngine: at startup use flag `-u=true` to enable Unikernel support on a worker node (it requires KVM and nested virtualization support) 

- Cluster/Root: The cluster aggregates the resources based on the available nodes architectures. This enables the dispatching of the Unikernel image to the correct hardware architecture. 

- Deployment descriptor:
  - `"arch":[]`: new architecture field where it's possible to specify all the hardware architectures compatible with the deployment.
  - `"code":""`: now supports links to `.tar.gz` kernel files. E.g. `http://<hosting-service-url>/nginx_x86.tar.gz`
  - `"virtualization": "unikernel"`: now it's possible to specify the virtualization type as unikernel.
  - `"cmd":[]`: if virtualization type is unikernel, this field now accepts the unikernel parameters (No need for a startup command on unikernels of course)
