### ISSUE TITLE
CI/CD

### ISSUE THREAD

**Issue by giobart** [oakestra/oakestra#92]
## Short
Automatic tests and docker images/binaries generation

## Proposal
The project must build automatically in the event of a successful test pipeline. This way, we always have consistent and automated versioning. 

## Rationale
This avoids confusing versioning, manual builds, and messy releases and reduces the risk of code not working. 

## Impact
All the components need to go through this process. 

## Development time
1 week for a base setup. This must be then gradually extended.

## Status
Ongoing

## Checklist
 
- [x] Discussed
- [ ] Documented
- [ ] Implemented
- [ ] Tested

**Comment by nitindermohan** [comment]
Please propose the server requirements for running the CI/CD pipeline in the documentation.

**Comment by giobart** [comment]
No sever required :) I managed to use GitHub workflows for this.
